version: "3.7"

services:
  server:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - HOST=
      - DB_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "4500:4500"

  postgres:
    image: postgres:14-alpine3.14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - go-gin-gorm-rest-example_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine3.14
    ports:
      - "6379:6379"

volumes:
  go-gin-gorm-rest-example_data:
